from powerline_shell.themes.default import DefaultColor

class Color(DefaultColor):
    USERNAME_FG = 137
    USERNAME_BG = 59
    USERNAME_ROOT_BG = 1

    HOSTNAME_FG = 137
    HOSTNAME_BG = 244

    HOME_SPECIAL_DISPLAY = False
    PATH_BG = 59
    PATH_FG = 137
    CWD_FG = 137
    SEPARATOR_FG = 137

    READONLY_BG = 1
    READONLY_FG = 15

    REPO_CLEAN_BG = 2  
    REPO_CLEAN_FG = 0
    REPO_DIRTY_BG = 1
    REPO_DIRTY_FG = 15

    JOBS_FG = 14
    JOBS_BG = 8

    CMD_PASSED_BG = 244
    CMD_PASSED_FG = 137
    CMD_FAILED_BG = 137
    CMD_FAILED_FG = 244

    SVN_CHANGES_BG = REPO_DIRTY_BG
    SVN_CHANGES_FG = REPO_DIRTY_FG

    VIRTUAL_ENV_BG = 2
    VIRTUAL_ENV_FG = 0

    AWS_PROFILE_FG = 14
    AWS_PROFILE_BG = 8

    TIME_FG = 8
    TIME_BG = 7